name: Automated Tests CI

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Web Tests and Generate HTML
        run: mvn clean verify -Pweb -Dsurefire.suiteXmlFiles=testng-web.xml -Dcucumber.filter.tags="@web"
      - name: Upload Web Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-web
          path: |
            target/cucumber-reports/web/Cucumber.json
            target/cucumber-html-reports/web/

  mobile-tests:
    runs-on: ubuntu-latest
    needs: []
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Mobile Tests and Generate HTML
        run: mvn clean verify -Pmobile -Dsurefire.suiteXmlFiles=testng-mobile.xml -Dcucumber.filter.tags="@mobile"
      - name: Upload Mobile Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-mobile
          path: |
            target/cucumber-reports/mobile/Cucumber.json
            target/cucumber-html-reports/mobile/
