name: Automated Tests CI

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Run Web tests
        run: |
          mvn -B verify -PBrowserStack,web -Dsurefire.suiteXmlFiles=testng.xml -Dcucumber.filter.tags="@web"

      - name: Upload Web reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-web
          path: |
            target/cucumber-reports/web/Cucumber.json
            target/cucumber-html-reports/web
            target/surefire-reports

  mobile-tests:
    runs-on: ubuntu-latest
    needs: []  # corre en paralelo
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Run Mobile tests
        run: |
          mvn -B verify -PBrowserStack,mobile -Dsurefire.suiteXmlFiles=testng.xml -Dcucumber.filter.tags="@mobile"

      - name: Upload Mobile reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-mobile
          path: |
            target/cucumber-reports/mobile/Cucumber.json
            target/cucumber-html-reports/mobile
            target/surefire-reports
