name: Automated Tests CI

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Web Tests
        run: mvn test -Pweb -Dsurefire.suiteXmlFiles=testng-web.xml -Dcucumber.filter.tags="@web" -Dbrowserstack=true
      - name: Upload Web Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-web
          path: |
            target/cucumber-reports/web/Cucumber.json
            target/cucumber-html-reports/web/

  mobile-android-tests:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Mobile Android Tests
        run: mvn test -Pmobile -Dsurefire.suiteXmlFiles=testng-mobile.xml -Dcucumber.filter.tags="@android" -Dbrowserstack=true
      - name: Upload Mobile Android Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-mobile-android
          path: |
            target/cucumber-reports/mobile/Cucumber.json
            target/cucumber-html-reports/mobile/

  mobile-ios-tests:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Mobile iOS Tests
        run: mvn test -Pmobile -Dsurefire.suiteXmlFiles=testng-mobile-iOS.xml -Dcucumber.filter.tags="@ios" -Dbrowserstack=true
      - name: Upload Mobile iOS Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports-mobile-ios
          path: |
            target/cucumber-reports/mobile/Cucumber.json
            target/cucumber-html-reports/mobile/
